# Generated by Django 5.1.1 on 2024-10-01 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('profession', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='user_images/')),
            ],
        ),
    ]
